apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: devan-sp
  name: dev-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: devan-sp
  type: NodePort
status:
  loadBalancer: {}
